### ISSUE TITLE
User Creation?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [twilio-labs/vestlus#26]
Based on looking at the Twillio Console, I can see that if I register a new user in the app, that user is being automagically created in Twillio as well.

But for the life of me I cannot figure where/how in the code for this app that is actually happening?

It appears the calls to /api/register are simply geared toward putting the user in the local JSON store only. Can you shed some light on where & how Twillio user creation happens?

Thanks

**Comment by stanlemon** [comment]
Ahoy! This is the best reference for what is going on here https://www.twilio.com/docs/conversations/create-tokens basically Twilio has a concept of a user for Conversations, but it doesn't manage authentication. You can manage your own authentication and then create a token for that user which maps to a user. Hope that helps!
