### ISSUE TITLE
Does Not Appear To Work Anymore

### ISSUE THREAD

**Issue by mfreeman-xtivia** [twilio-labs/vestlus#31]
git clone, npm install, npm run start results in:

file:///home/dev/projects/citci/vestlus/node_modules/@stanlemon/server-with-auth/src/data/simple-users-dao.js:1
[server:start] import { LowSync, JSONFileSync, MemorySync } from "lowdb";
[server:start]                   ^^^^^^^^^^^^
[server:start] SyntaxError: The requested module 'lowdb' does not provide an export named 'JSONFileSync'

**Comment by stanlemon** [comment]
This is related to a change downstream in lowdb. They split their package up. I fixed it in https://github.com/stanlemon/javascript/commit/57b326834f05ce4bb7a2c0454dd88f16333946af and then updated the dependency in Vestlus, so it should work now. Thanks for reporting it!
